language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install pandoc
install:
  - pandoc --from=markdown --to=rst --output=README.rst README.md
  - pip install mock
# command to run tests
script:
  - python setup.py install test
